
services:
  Client:
    image: abhaypratapsingh7704866570/mern-portfolio-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - Server
    restart: unless-stopped

  Server:
    image: abhaypratapsingh7704866570/mern-portfolio-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: